// web/src/lib/components/ai-elements/copy-button/CopyButton.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button/index.js';
	import { UseClipboard } from '$lib/hooks/use-clipboard.svelte';
	import { cn } from '$lib/utils';
	import CheckIcon from '@lucide/svelte/icons/check';
	import CopyIcon from '@lucide/svelte/icons/copy';
	import XIcon from '@lucide/svelte/icons/x';
	import { scale } from 'svelte/transition';
	import type { CopyButtonProps } from './types';

	let {
		ref = $bindable(null),
		text,
		icon,
		animationDuration = 500,
		variant = 'ghost',
		size = 'icon',
		onCopy,
		class: className,
		tabindex = -1,
		children
	}: CopyButtonProps = $props();
	let buttonSize = $derived(size === 'icon' && children ? 'default' : size);

	let clipboard = new UseClipboard();
</script>

<Button
	bind:ref
	{variant}
	size={buttonSize}
	{tabindex}
	class={cn('flex items-center gap-2', className)}
	type="button"
	name="copy"
	onclick={async () => {
		const status = await clipboard.copy(text);

		onCopy?.(status);
	}}
>
	{#if clipboard.status === 'success'}
		<div in:scale={{ duration: animationDuration, start: 0.85 }}>
			<CheckIcon tabindex={-1} strokeWidth={1.8} />
			<span class="sr-only">Copied</span>
		</div>
	{:else if clipboard.status === 'failure'}
		<div in:scale={{ duration: animationDuration, start: 0.85 }}>
			<XIcon tabindex={-1} strokeWidth={1.8} />
			<span class="sr-only">Failed to copy</span>
		</div>
	{:else}
		<div in:scale={{ duration: animationDuration, start: 0.85 }}>
			{#if icon}
				{@render icon()}
			{:else}
				<CopyIcon tabindex={-1} strokeWidth={1.8} />
			{/if}
			<span class="sr-only">Copy</span>
		</div>
	{/if}
	{@render children?.()}
</Button>

// web/components/ui/copy-button.tsx
"use client"

import { Check, Copy } from "lucide-react"

import { cn } from "@/lib/utils"
import { useCopyToClipboard } from "@/hooks/use-copy-to-clipboard"
import { Button } from "@/components/ui/button"

type CopyButtonProps = {
  content: string
  label?: string
}

export function CopyButton({ content, label }: CopyButtonProps) {
  const { isCopied, handleCopy } = useCopyToClipboard({
    text: content,
  })

  return (
    <Button
      variant="ghost"
      size={label ? "default" : "icon"}
      className={cn("relative", !label && "h-6 w-6")}
      aria-label="Copy to clipboard"
      onClick={handleCopy}
    >
      <span className="relative inline-flex h-4 w-4 items-center justify-center">
        <Check
          className={cn(
            "absolute h-4 w-4 transition-transform ease-in-out",
            isCopied ? "scale-100" : "scale-0"
          )}
        />
        <Copy
          className={cn(
            "h-4 w-4 transition-transform ease-in-out",
            isCopied ? "scale-0" : "scale-100"
          )}
        />
      </span>
      {label ? <span>{label}</span> : null}
    </Button>
  )
}
