// web/components/ai-elements/checkpoint.tsx
import { Separator } from "@/components/ui/separator"
import { cn } from "@/lib/utils"
import type { LucideProps } from "lucide-react"
import { BookmarkIcon } from "lucide-react"
import type { HTMLAttributes } from "react"

export type CheckpointProps = HTMLAttributes<HTMLDivElement>

export const Checkpoint = ({ className, children, ...props }: CheckpointProps) => (
  <div
    className={cn("text-muted-foreground flex items-center gap-0.5 overflow-hidden", className)}
    {...props}
  >
    {children}
    <Separator />
  </div>
)

export type CheckpointIconProps = LucideProps

export const CheckpointIcon = ({ className, children, ...props }: CheckpointIconProps) =>
  children ?? <BookmarkIcon className={cn("size-4 shrink-0", className)} {...props} />

// web/src/lib/components/ai-elements/checkpoint/Checkpoint.svelte
<script lang="ts" module>
	import { cn, type WithElementRef } from '$lib/utils';
	import type { HTMLAttributes } from 'svelte/elements';
	import type { Snippet } from 'svelte';

	export interface CheckpointProps extends WithElementRef<HTMLAttributes<HTMLDivElement>> {
		children?: Snippet;
	}
</script>

<script lang="ts">
	import { Separator } from '$lib/components/ui/separator';

	let {
		class: className,
		children,
		ref = $bindable(null),
		...restProps
	}: CheckpointProps = $props();
</script>

<div
	bind:this={ref}
	class={cn('flex min-w-0 items-center gap-0.5 overflow-hidden text-muted-foreground', className)}
	{...restProps}
>
	{@render children?.()}
	<Separator class="min-w-0 flex-1 shrink" />
</div>
